apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts

spec:
  replicas: 2
  strategy: 
    # recreate causa indisponibilidade
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10% 
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
      containers:
        - name: app-ts
          image: guilherme1212/app-ts:v8
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-ts
            - secretRef:
                name: app-ts-secrets
          # env:
          #  - name: APP
          #    valueFrom:
          #      configMapKeyRef:
          #        name: app-ts
          #        key: app-name
          #  - name: API_KEY
          #    valueFrom:
          #      secretKeyRef:
          #        name: app-ts-secrets
          #        key: api-key
          ports:
            - containerPort: 3000

          # garanti que sua aplicação que está rodando em container subiu
          startupProbe:
            # executar script dentro do startupProbe
            # exec:
            #   command:
            #     - /bin/sh
            #     - -c
            #     - check.sh
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10

          # Valida se a aplicação está pronta para receber tráfego
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 5

          # sondagem de vivacidade, olha a aplicação de tempos em tempos para ver se ela está viva
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 192Mi

          volumeMounts:
            - name: app-ts-data
              # montagem dentro do container
              mountPath: /usr/src/app/uploads
      volumes:
        - name: app-ts-data
          persistentVolumeClaim:
            claimName: first-pvc
            