apiVersion: v1
kind: Secret

metadata:
  name: app-ts-secrets
type: Opaque
data:
  # asjfksdjfklsjdlf
  # usando env
  # api-key: YXNqZmtzZGpma2xzamRsZgo=
  # usando envFrom
  API_KEY: YXNqZmtzZGpma2xzamRsZgo=
  
